import 'restaurant_model.dart';

const List<Restaurant> mockRestaurants = [
  Restaurant(
    id: 'r1',
    name: "Nonna's Kitchen",
    cuisine: 'Italian',
    mealDbCategory: 'Pasta',
    imageUrl: 'https://www.themealdb.com/images/category/pasta.png',
    rating: 4.7,
    deliveryTimeMinutes: 25,
    deliveryFee: 1.99,
  ),
  Restaurant(
    id: 'r2',
    name: 'Ocean Breeze',
    cuisine: 'Seafood',
    mealDbCategory: 'Seafood',
    imageUrl: 'https://www.themealdb.com/images/category/seafood.png',
    rating: 4.5,
    deliveryTimeMinutes: 35,
    deliveryFee: 2.49,
  ),
  Restaurant(
    id: 'r3',
    name: 'Green Bowl',
    cuisine: 'Vegetarian',
    mealDbCategory: 'Vegetarian',
    imageUrl: 'https://www.themealdb.com/images/category/vegetarian.png',
    rating: 4.6,
    deliveryTimeMinutes: 20,
    deliveryFee: 0.99,
  ),
  Restaurant(
    id: 'r4',
    name: 'Grill House',
    cuisine: 'Beef & Grill',
    mealDbCategory: 'Beef',
    imageUrl: 'https://www.themealdb.com/images/category/beef.png',
    rating: 4.4,
    deliveryTimeMinutes: 30,
    deliveryFee: 2.99,
  ),
  Restaurant(
    id: 'r5',
    name: 'Golden Wok',
    cuisine: 'Chicken & Asian',
    mealDbCategory: 'Chicken',
    imageUrl: 'https://www.themealdb.com/images/category/chicken.png',
    rating: 4.8,
    deliveryTimeMinutes: 22,
    deliveryFee: 1.49,
  ),
  Restaurant(
    id: 'r6',
    name: 'Sweet Tooth',
    cuisine: 'Desserts',
    mealDbCategory: 'Dessert',
    imageUrl: 'https://www.themealdb.com/images/category/dessert.png',
    rating: 4.9,
    deliveryTimeMinutes: 18,
    deliveryFee: 1.99,
  ),
  Restaurant(
    id: 'r7',
    name: 'Breakfast Club',
    cuisine: 'Breakfast',
    mealDbCategory: 'Breakfast',
    imageUrl: 'https://www.themealdb.com/images/category/breakfast.png',
    rating: 4.3,
    deliveryTimeMinutes: 15,
    deliveryFee: 0.99,
  ),
  Restaurant(
    id: 'r8',
    name: 'Pasta Fresca',
    cuisine: 'Vegan',
    mealDbCategory: 'Vegan',
    imageUrl: 'https://www.themealdb.com/images/category/vegan.png',
    rating: 4.5,
    deliveryTimeMinutes: 28,
    deliveryFee: 2.49,
  ),
];